import React from "react";
import SessionCard from "./session-card";
import { getSessionListAction } from "@/server/actions/sessions-action";
import { cookies } from "next/headers";
import { lucia } from "@/lib/auth";

export const metadata = {
  title: "Settings | My Portfolio",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function ActiveSessionsPage() {
  const sessions = await getSessionListAction();
  const sessionId = cookies().get(lucia.sessionCookieName)?.value;

  if (!sessionId) return null;

  return (
    <>
      <div className="flex items-center">
        <h1 className="text-lg font-semibold md:text-2xl">Active Sessions</h1>
      </div>
      <div className="flex flex-col items-center gap-4">
        {sessions.map((session) => (
          <SessionCard
            key={session.id}
            {...session}
            currentSessionId={sessionId}
          />
        ))}
      </div>
    </>
  );
}
