import { api, HydrateClient } from "@/trpc/server";
import { type Metadata } from "next";

interface DashboardExperienceLayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Experiences | My Portfolio",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function DashboardExperienceLayout({
  children,
}: DashboardExperienceLayoutProps) {
  api.experience.all.prefetch();

  return (
    <section>
      <div className="flex items-center">
        <h1 className="text-lg font-semibold md:text-2xl">Experiences</h1>
      </div>
      <div className="flex flex-col flex-wrap gap-4 p-4 lg:gap-6 lg:p-6">
        <HydrateClient>{children}</HydrateClient>
      </div>
    </section>
  );
}
