import React from "react";

export const metadata = {
  title: "Experiences | My Portfolio",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function ExperiencesPage() {
  return (
    <>
      <div className="flex items-center">
        <h1 className="text-lg font-semibold md:text-2xl">Experiences</h1>
      </div>
      {/* <DashboardSection /> */}
    </>
  );
}
